apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-customer-payment-secret
type: Opaque
data:
  CUSTOMER_API_KEY: {{ .Values.customerService.apiKey | b64enc }}
  PAYMENT_TOKEN: {{ .Values.paymentService.paymentToken | b64enc }}
