apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
spec:
  replicas: {{ .Values.orderService.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          image: {{ .Values.orderService.image }}
          ports:
            - containerPort: {{ .Values.orderService.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.orderService.configMapName }}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-order-service-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-order-service-secret
                  key: DB_PASSWORD
