apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.orderService.configMapName }}
data:
  application.properties: |
    server.port={{ .Values.orderService.port }}
    spring.datasource.url=jdbc:mysql://mysql:3306/orderdb
    spring.datasource.username={{ .Values.orderService.dbUsername | default "user" }}
    spring.datasource.password={{ .Values.orderService.dbPassword | default "pass" }}
