apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:1.0
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
          env:
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: customer-payment-secret
                      key: CUSTOMER_API_KEY
      volumes:
        - name: config-volume
          configMap:
            name: customer-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - port: 80
      targetPort: 8085
      nodePort: 30082
